vehiculos/urls.py
from django.contrib import admin
from django.urls import path
from vehiculos_app.views import create_view, list_view,update_view, delete_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', list_view), 
    path('create/', create_view), 
    path('update/<id>', update_view),
    path('delete/<id>', delete_view),
       
]

vehiculos_app/models.py
from django.db import models

# Create your models here.
class vehicle(models.Model):
    COLOR=(
        ('1','ROJO'),
        ('2','AZUL'),
        ('3','VERDE'),
    )
    placa=models.CharField(max_length=6)
    marca=models.CharField(max_length=10)
    color_vehiculo=models.CharField('color',max_length=1,choices=COLOR)
    modelo=models.IntegerField()


    def __str__(self):
        return self.placa

vehiculos_app/forms.py
from django import forms
from .models import vehicle
 
 
# creating a form
class VehicleForm(forms.ModelForm):
 
    # create meta class
    class Meta:
        # specify model to be used
        model = vehicle
 
        # specify fields to be used
        fields = [
            "placa",
            "marca",
            "modelo",
            "color_vehiculo"
        ]

        labels = {
            'placa': 'Número de placa',
            'marca': 'Marca del vehículo',
            'modelo': 'Modelo del vehículo',
            'color_vehiculo': 'Color del vehículo'
        }

        widgets = {
            'placa': forms.TextInput(attrs={'class': 'form-control'}),
            'marca': forms.TextInput(attrs={'class': 'form-control'}),
            'modelo': forms.TextInput(attrs={'class': 'form-control'}),
            'color_vehiculo': forms.Select(attrs={'class': 'form-control'}),
        }

vehiculos_app/views.py
from django.shortcuts import render,HttpResponseRedirect,get_object_or_404

# Create your views here.

 
# relative import of forms
from .models import vehicle
from .forms import VehicleForm

def create_view(request):
    context ={}
    form = VehicleForm(request.POST or None)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect("/")
         
    context['form']= form
    return render(request, "create_view.html", context)

def list_view(request):
    context ={}
    context['dataset']= vehicle.objects.all()
    return render(request, "list_view.html", context)

def update_view(request, id):
    context = {}
    
    obj = get_object_or_404(vehicle, id=id)
    
    form = VehicleForm(request.POST or None, instance=obj)
    
    if form.is_valid():
        form.save()
        return HttpResponseRedirect("/")
    
    context['form']= form
    
    
    return render(request, "update_view.html", context)

def delete_view(request, id):
    context = {}
    
    obj = get_object_or_404(vehicle, id=id)
    
    if request.method == 'POST':
        obj.delete()
        return HttpResponseRedirect("/")
    return render(request, "delete_view.html", context)

vehiculos_app/templates/base.html
<!-- base.html -->
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Vehículos{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <!-- Enlace a Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

vehiculos_app/templates/create_view.html
<!-- home.html -->
{% extends 'base.html' %}

{% block content %}

<h1>Nuevo Vehículo</h1>


<form method="POST" enctype="multipart/form-data">
 
    <!-- Security token -->
    {% csrf_token %}
 
    <!-- Using the formset -->
    <!-- {{ form.as_p }} -->
    <div class="form-group">
        {{ form.placa.label_tag }}
        {{ form.placa }}
    </div>

    <div class="form-group">
        {{ form.marca.label_tag }}
        {{ form.marca }}
    </div>

    <div class="form-group">
        {{ form.modelo.label_tag }}
        {{ form.modelo }}
    </div>

    <div class="form-group">
        {{ form.color_vehiculo.label_tag }}
        {{ form.color_vehiculo }}
    </div>

   
     
    <input type="submit" value="Guardar" class="btn btn-primary">
</form>


{% endblock %}

vehiculos_app/templates/delete_view.html
{% extends 'base.html' %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        Esta seguro de eliminar el elemento ?
        <input type="submit" value="Si" class="btn btn-primary" />
        <a href="/" class="btn btn-secondary">Cancelar </a>
    </form>
{% endblock %}

vehiculos_app/templates/hello_world.html
<!-- home.html -->
{% extends 'base.html' %}

{% block content %}

<h1>Hola mundo</h1>

{% endblock %}

vehiculos_app/templates/list_view.html
<!-- home.html -->
{% extends 'base.html' %}

{% block content %}

<h1>Vehículos</h1>


<a href="/create/" ><i class="fa fa-plus"></i></a>
<table class="table table-striped">
        <thead class="thead-dark">
        <tr>
            <th>Placa</th>
            <th>Marca</th>
            <th>Color</th>
            <th>Modelo</th>
            <th>&nbsp;</th>
        </tr>
        </thead>
        <tbody>
            {% for data in dataset %}
            <tr>
                <td>{{ data.placa }}</td>
                <td>{{ data.marca }}</td>
                <td>{{ data.get_color_vehiculo_display }}</td>
                <td>{{ data.modelo }}</td>
                <td>
                    <a href="/update/{{ data.id }}"><i class="fa fa-edit"></i></a>
                    <!-- <a href="/delete/{{ data.id }}"><i class="fa fa-trash"></i></a> -->
                    <a href="#" data-toggle="modal" data-target="#deleteModal{{ data.id }}"><i class="fa fa-trash"></i></a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table> <!-- ajustar la ruta y lo logramos en el archivo utls.py -->


{% for data in dataset %}
<!-- Modal -->
<div class="modal fade" id="deleteModal{{ data.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form action="/delete/{{ data.id }}" method="post">
                {% csrf_token %}
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Eliminar registro</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    Desea eliminar el registro con ID: {{ data.id }}?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                    <button type="submit" class="btn btn-primary">Eliminar</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endfor %}


{% endblock %}

vehiculos_app/templates/update_view.html
<!-- home.html -->
{% extends 'base.html' %}

{% block content %}

<h1>Actualizar Vehículo</h1>


<form method="POST" enctype="multipart/form-data">
 
    <!-- Security token -->
    {% csrf_token %}
 
    <!-- Using the formset -->
    <!-- {{ form.as_p }} -->
    <div class="form-group">
        {{ form.placa.label_tag }}
        {{ form.placa }}
    </div>

    <div class="form-group">
        {{ form.marca.label_tag }}
        {{ form.marca }}
    </div>

    <div class="form-group">
        {{ form.modelo.label_tag }}
        {{ form.modelo }}
    </div>

    <div class="form-group">
        {{ form.color_vehiculo.label_tag }}
        {{ form.color_vehiculo }}
    </div>

   
<!--guardar o Actualizar-->
    <input type="submit" value="Guardar" class="btn btn-primary">
</form>


{% endblock %}